### ISSUE TITLE
WIF private key is Bitcoin Format, not Vertcoin format

### ISSUE THREAD

**Issue by 1MichaS1** [vertcoin-project/vertaddress.org#1]
Generated WIF private key (starting with a 5...) won't be recognized by wallets like Coinomi, rendering the Vertcoins unspendable. It would be correct to generate the private key in Vertcoin format (starting with a 7...).

See walletgenerator.net to see how it should work correctly.

**Comment by metalicjames** [comment]
Core and Electrum will generate and accept '5' prefixed private keys. I
can't speak for coinomi because it's not developed by us.

**Comment by gertjaap** [comment]
The format is conform Vertcoin's reference implementation (Core). If you dump private keys there, you get the same format as vertaddress.org. The format by walletgenerator.net always had to be converted to be able to import to our own Core wallet.

Agree with @metalicjames that we shouldn't change this, so i'm closing this issue.

Pardon the delay, by the way.
